<?php

namespace App\Models;

use App\Support\Auditing\Auditable;
use App\Services\ActiveInstitutionContext;
use App\Services\EquipoInternalCodeService;
use App\Services\EquipoStatusResolver;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class Equipo extends Model
{
    use Auditable, HasFactory;

    public const INTERNAL_CODE_PREFIX = 'GA-EQ-';
    // New autogenerated codes use a 6-digit minimum sequence. Existing legacy codes can keep wider padding.
    public const INTERNAL_CODE_PAD_LENGTH = 6;

    public const ESTADO_OPERATIVO = 'operativo';
    public const ESTADO_PRESTADO = 'prestado';
    public const ESTADO_EN_MANTENIMIENTO = 'mantenimiento';
    public const ESTADO_MANTENIMIENTO = self::ESTADO_EN_MANTENIMIENTO;
    public const ESTADO_FUERA_DE_SERVICIO = 'fuera_de_servicio';
    public const ESTADO_BAJA = 'baja';

    public const ESTADOS = [
        self::ESTADO_OPERATIVO,
        self::ESTADO_PRESTADO,
        self::ESTADO_EN_MANTENIMIENTO,
        self::ESTADO_FUERA_DE_SERVICIO,
        self::ESTADO_BAJA,
    ];

    protected $fillable = [
        'uuid',
        'tipo',
        'tipo_equipo_id',
        'marca',
        'modelo',
        'numero_serie',
        'bien_patrimonial',
        'mac_address',
        'estado',
        'equipo_status_id',
        'fecha_ingreso',
        'oficina_id',
    ];

    protected $guarded = ['id', 'created_at', 'updated_at'];

    protected static function booted(): void
    {
        static::saving(function (Equipo $equipo): void {
            $equipo->normalizeTrackedIdentifiers();
        });

        static::creating(function (Equipo $equipo): void {
            if (Schema::hasColumn($equipo->getTable(), 'uuid') && empty($equipo->uuid)) {
                $equipo->uuid = (string) Str::uuid();
            }

            if (
                Schema::hasColumn($equipo->getTable(), 'codigo_interno')
                && Schema::hasTable('internal_code_sequences')
                && empty($equipo->codigo_interno)
            ) {
                $equipo->codigo_interno = app(EquipoInternalCodeService::class)->next();
            }

            if (! Schema::hasColumn($equipo->getTable(), 'equipo_status_id')) {
                return;
            }

            if ($equipo->equipo_status_id === null) {
                $equipo->equipo_status_id = app(EquipoStatusResolver::class)->resolveOrCreateOperativaId();
            }
        });
    }

    protected function casts(): array
    {
        return ['fecha_ingreso' => 'date'];
    }

    public function oficina(): BelongsTo
    {
        return $this->belongsTo(Office::class, 'oficina_id');
    }

    public function tipoEquipo(): BelongsTo
    {
        return $this->belongsTo(TipoEquipo::class);
    }

    public function equipoStatus(): BelongsTo
    {
        return $this->belongsTo(EquipoStatus::class, 'equipo_status_id');
    }

    public function movimientos(): HasMany
    {
        return $this->hasMany(Movimiento::class)->orderByDesc('fecha');
    }

    public function mantenimientos(): HasMany
    {
        return $this->hasMany(Mantenimiento::class)->orderByDesc('fecha')->orderByDesc('id');
    }

    public function recepcionesTecnicas(): HasMany
    {
        return $this->hasMany(RecepcionTecnica::class)->orderByDesc('ingresado_at')->orderByDesc('id');
    }

    public function recepcionTecnicaAbierta(): HasOne
    {
        return $this->hasOne(RecepcionTecnica::class)
            ->whereIn('estado', RecepcionTecnica::ESTADOS_ABIERTOS)
            ->latestOfMany('ingresado_at');
    }

    public function mantenimientoExternoAbierto(): HasOne
    {
        return $this->hasOne(Mantenimiento::class)
            ->where('tipo', Mantenimiento::TIPO_EXTERNO)
            ->whereNull('fecha_egreso_st');
    }

    public function actas(): BelongsToMany
    {
        return $this->belongsToMany(Acta::class, 'acta_equipo')->withPivot(['cantidad', 'accesorios', 'institucion_origen_id', 'institucion_origen_nombre', 'servicio_origen_id', 'servicio_origen_nombre', 'oficina_origen_id', 'oficina_origen_nombre']);
    }

    public function historial(): HasMany
    {
        return $this->hasMany(EquipoHistorial::class)->latest('fecha');
    }

    public function documents(): MorphMany
    {
        return $this->morphMany(Document::class, 'documentable')->latest();
    }

    public function documentosCentralizados(): HasMany
    {
        return $this->hasMany(EquipoDocumento::class)
            ->orderByDesc('fecha_documento')
            ->latest();
    }

    public function tienePrestamoActivo(): bool
    {
        return Movimiento::query()
            ->where('equipo_id', $this->id)
            ->where('tipo_movimiento', Movimiento::TIPO_PRESTAMO)
            ->whereNull('fecha_devolucion_real')
            ->exists();
    }

    /**
     * @return array{institucion_id:int|null,servicio_id:int|null,oficina_id:int|null}
     */
    public function ubicacionActual(): array
    {
        $this->loadMissing('oficina.service.institution');

        return [
            'institucion_id' => $this->oficina?->service?->institution?->id,
            'servicio_id' => $this->oficina?->service?->id,
            'oficina_id' => $this->oficina?->id,
        ];
    }

    public function isOperativa(): bool
    {
        return $this->equipoStatus?->code === EquipoStatus::CODE_OPERATIVA;
    }

    public function isEnServicioTecnico(): bool
    {
        return $this->equipoStatus?->code === EquipoStatus::CODE_EN_SERVICIO_TECNICO;
    }

    public function tieneMantenimientoExternoAbierto(): bool
    {
        if ($this->relationLoaded('mantenimientoExternoAbierto')) {
            return $this->mantenimientoExternoAbierto !== null;
        }

        return $this->mantenimientoExternoAbierto()->exists();
    }

    public function isBaja(): bool
    {
        return $this->equipoStatus?->code === EquipoStatus::CODE_BAJA;
    }

    public function scopeVisibleToUser(Builder $query, ?User $user): Builder
    {
        $scopeIds = app(ActiveInstitutionContext::class)->globalAdministrationScopeIds($user);

        if ($scopeIds === null) {
            return $query;
        }

        if ($scopeIds === []) {
            return $query->whereRaw('1 = 0');
        }

        return $query->whereHas('oficina.service', function (Builder $serviceQuery) use ($scopeIds): void {
            $serviceQuery->whereIn('institution_id', $scopeIds);
        });
    }

    /**
     * @param array{tipo?:mixed,marca?:mixed,modelo?:mixed,estado?:mixed} $filters
     */
    public function scopeApplyIndexFilters(Builder $query, array $filters): Builder
    {
        $tipo = trim((string) ($filters['tipo'] ?? ''));
        $marca = trim((string) ($filters['marca'] ?? ''));
        $modelo = trim((string) ($filters['modelo'] ?? ''));
        $estado = (string) ($filters['estado'] ?? '');

        return $query
            ->when($tipo !== '', fn (Builder $builder) => $builder->where('tipo', 'ilike', "%{$tipo}%"))
            ->when($marca !== '', fn (Builder $builder) => $builder->where('marca', 'ilike', "%{$marca}%"))
            ->when($modelo !== '', fn (Builder $builder) => $builder->where('modelo', 'ilike', "%{$modelo}%"))
            ->when(in_array($estado, self::ESTADOS, true), fn (Builder $builder) => $builder->where('estado', $estado));
    }

    public function scopeSearchIndex(Builder $query, string $search): Builder
    {
        $search = trim($search);

        if ($search === '') {
            return $query;
        }

        $like = "%{$search}%";

        return $query->where(function (Builder $builder) use ($like): void {
            $builder
                ->where('tipo', 'ilike', $like)
                ->orWhere('marca', 'ilike', $like)
                ->orWhere('modelo', 'ilike', $like)
                ->orWhere('numero_serie', 'ilike', $like)
                ->orWhere('bien_patrimonial', 'ilike', $like)
                ->orWhere('mac_address', 'ilike', $like)
                ->orWhere('codigo_interno', 'ilike', $like)
                ->orWhereHas('oficina', function (Builder $officeQuery) use ($like): void {
                    $officeQuery
                        ->where('nombre', 'ilike', $like)
                        ->orWhereHas('service', function (Builder $serviceQuery) use ($like): void {
                            $serviceQuery
                                ->where('nombre', 'ilike', $like)
                                ->orWhereHas('institution', fn (Builder $institutionQuery) => $institutionQuery->where('nombre', 'ilike', $like));
                        });
                });
        });
    }

    public static function formatCodigoInterno(int $sequence): string
    {
        return sprintf('%s%0'.self::INTERNAL_CODE_PAD_LENGTH.'d', self::INTERNAL_CODE_PREFIX, $sequence);
    }

    public function primaryIdentifier(): string
    {
        return $this->codigo_interno
            ?: $this->numero_serie
            ?: $this->bien_patrimonial
            ?: ('ID '.$this->id);
    }

    public function reference(): string
    {
        return collect([
            $this->tipo ?: 'Equipo',
            $this->codigo_interno ? 'CI '.$this->codigo_interno : null,
            $this->numero_serie ? 'NS '.$this->numero_serie : null,
            $this->bien_patrimonial ? 'BP '.$this->bien_patrimonial : null,
        ])->filter()->implode(' / ');
    }

    private function normalizeTrackedIdentifiers(): void
    {
        foreach (['numero_serie', 'bien_patrimonial', 'mac_address', 'codigo_interno'] as $attribute) {
            $value = $this->getAttribute($attribute);

            if ($value === null) {
                continue;
            }

            $trimmed = trim((string) $value);
            $trimmed = $attribute === 'codigo_interno' ? strtoupper($trimmed) : $trimmed;

            $this->setAttribute($attribute, $trimmed === '' ? null : $trimmed);
        }
    }
}
