extension_dir="C:/php-8.3.22/ext"
openssl.cafile=
date.timezone=America/Argentina/Buenos_Aires
memory_limit=512M
extension=curl
extension=fileinfo
extension=mbstring
extension=openssl
extension=pdo_sqlite
extension=sqlite3
extension=zip
extension=intl
extension=gd
extension=sodium
